# Generated by Django 2.0.7 on 2018-08-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('order_total_products', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.PositiveSmallIntegerField()),
                ('cart_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_unit_price', models.FloatField()),
                ('product_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_description', models.CharField(max_length=255)),
                ('shipping_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ordercart',
            name='cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.OrderStatus'),
        ),
    ]
