# Generated by Django 2.0.7 on 2018-08-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20180828_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_weight',
        ),
    ]
