# Generated by Django 2.0.7 on 2018-08-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_product_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'OrderStatus'},
        ),
    ]
